#!/usr/bin/env sh

version() {
	echo "Template v1.1.4"
}

usage() {
	cat << EOF
$(version)
Usage: template [options] [path]
Template lets one use handlebars in your files and paste the output.

Available options are:
  -h		show this help
  -v		print the version
  -o		set the output dir (defaults to ./out)

With no path given the default is ..

Examples:
  template static/

MIT License

Copyright (c) 2022 Brian Mayer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
}

template() {
	[ -z $1 ] || echo "$1" | grep -q .tpl || { cat "$1"; return; }
	while IFS=  read -r line
	do
		if echo "$line" | grep -q '{{!'
		then
			pre="${line%\{\{*}"
			rest="${line#*\{\{\!}"
			if echo "$line" | grep -q '}}'
			then
				cmd="${rest%\}\}*}"
				rest="${rest#*\}\}}"
			else
				cmd="$rest"
				while IFS=  read -r l
				do
					cmd="$cmd\n${l%\}\}*}"
					echo "$l" | grep -q '}}' && rest="${l#*\}\}}" && break
				done
			fi
			printf -- "$pre"
			printf -- "$cmd" | sh
			printf -- "$rest"
		elif echo "$line" | grep -q '{{'
		then
			# replace files in {{}}
			template $(echo "$line" | sed 's:{{\(.*\)}}:\1:g')
		else
			printf -- "%s\n" "$line"
		fi
	done
}

# Command line options
while getopts hv: name
do
	case $name in
		h) usage && exit 0;;
		v) version && exit 0;;
		?) usage && exit 1;;
		*) args+="$name" ;;
	esac
done
if [ -f "$1" ]
then
	template < "$1"
else
	template
fi
