#!/bin/bash

version() {
	echo "Template v0.5.0"
}

usage() {
	cat << EOF
template v0.5.0
Usage: template [options] [path]
Template lets one use handlebars in your files and paste the output.

Available options are:
  -h		show this help
  -v		print the version

With no path given the default is ..

Examples:
  template static/

MIT License

Copyright (c) 2021 Brian Mayer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
}

template() {
	for file in "$@"
	do
		[[ "$file" =~ .+\.tpl ]] || { cat "$file"; continue; }
		while IFS=  read -r line
		do
			if echo "$line" | grep -q '{{!'
			then
				# replace {{!}} commands
				echo "$line" | sed 's:\s*{{\!\s*\(.*\)\s*}}:\1:g' | sh
			elif grep -q '{{' <<< "$line"
			then
				# replace files in {{}}
				template $(echo "$line" | sed 's:\s*{{\s*\(.*\)\s*}}:\1:g')
			else
				printf "%s\n" "$line"
			fi
		done < "$file"
	done
}

# Command line options
while getopts hv name
           do
               case $name in
               h)    usage && exit 0;;
               v)    version && exit 0;;
               ?)    usage && exit 1;;
               esac
           done

[[ -d out ]] || mkdir out

find "$@" -type f | while read -r tpl; do
echo "$tpl"
mkdir -p $(dirname out/$tpl)
template "$tpl" > "out/${tpl%.tpl}"
done

